apiVersion: v1
kind: Service
metadata:
  name:  httpd-service-devops
  namespace:  httpd-namespace-devops
spec:
  type: NodePort
  selector:
    app: httpd_app_devops
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
